name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: Run workglow in debug mode
        required: false
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] print start-up date"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by ${{github.event_name}}"
          echo "Branch: ${{ github.ref }}"
          echo " Commit SHA: ${{github.sha}} "
          echo " Runs on: ${{runner.os}} "

      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "triggered from main"

      - name: Greeting
        run: echo "Hello, world"
