name: using variables

on:
  push:
  workflow_dispatch:
env:
  WORKFLOW_VAR: I'm at workflow env
  OVERWRITTEN: I will be overwritten
jobs:
  echo:
    runs-on: ubuntu-latest
    needs: echoAgain
    env:
      JOB_VAR: Im job var
      OVERWRITTEN: Overwritten at job level
    steps:
      - name: env var
        env:
          STEP_VAR: Im a step env var
          step_var2: im another step var
        run: |
          echo "WORKFLOW_VAR = $WORKFLOW_VAR"
          echo "JOB_VAR = $JOB_VAR"
          echo "STEP_VAR = $STEP_VAR"
          echo "step_var2 = $step_var2"
          echo "OVERWRITTEN = $OVERWRITTEN"
  echoAgain:
    runs-on: ubuntu-latest
    steps:
      - name: print echoAgain 
        run: echo "Echo again runs"